### PR TITLE
 add read aloud button and accessibility js

### PR DESCRIPTION
**Pull request by Reina2024**
added read aloud button

### CODE REVIEW

**Review by JamesWilliamParker — CHANGES_REQUESTED** [review]
class has a capital letter "Readbtn"

**Review by JamesWilliamParker — APPROVED** [review]
Jose remembered how to do this!! Yay!

**Review by JamesWilliamParker — APPROVED** [review]
Yay!

**Review by Uwttn — APPROVED** [review]
James is great!

**Review by Uwttn — APPROVED** [review]
James is great!

**Pull request merged**
